<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:loc="http://ws.vega-systems.com/LocproTNS">
   <soapenv:Header/>
   <soapenv:Body>
      <loc:WS_WCLIENT_RECH_2>
         <loc:COOKIE_F903KY>?</loc:COOKIE_F903KY>
         <!--Optional:-->
         <loc:Region>?</loc:Region>
         <!--Optional:-->
         <loc:CritereClient>
            <!--Optional:-->
            <loc:RaisonSociale>?</loc:RaisonSociale>
            <!--Optional:-->
            <loc:CodeClient>?</loc:CodeClient>
            <!--Optional:-->
            <loc:NumeroTVAIntracommunautaire>?</loc:NumeroTVAIntracommunautaire>
            <!--Optional:-->
            <loc:Siret>?</loc:Siret>
            <!--Optional:-->
            <loc:Codepostal>?</loc:Codepostal>
            <!--Optional:-->
            <loc:CommunicationsClients>
               <!--Zero or more repetitions:-->
               <loc:CommunicationsClient>
                  <loc:Type>?</loc:Type>
                  <loc:Nature>?</loc:Nature>
                  <loc:Value>?</loc:Value>
               </loc:CommunicationsClient>
            </loc:CommunicationsClients>
            <!--Optional:-->
            <loc:CodeChantier>?</loc:CodeChantier>
            <!--Optional:-->
            <loc:IsActif>?</loc:IsActif>
         </loc:CritereClient>
         <!--Optional:-->
         <loc:Clients>
            <!--Zero or more repetitions:-->
            <loc:Client>
               <!--Optional:-->
               <loc:FicheClient>
                  <!--Optional:-->
                  <loc:LastModif>?</loc:LastModif>
                  <!--Optional:-->
                  <loc:RaisonSociale>?</loc:RaisonSociale>
                  <!--Optional:-->
                  <loc:IsActif>?</loc:IsActif>
                  <!--Optional:-->
                  <loc:NumeroTVAIntracommunautaire>?</loc:NumeroTVAIntracommunautaire>
                  <!--Optional:-->
                  <loc:Siret>?</loc:Siret>
                  <!--Optional:-->
                  <loc:CodeClient>?</loc:CodeClient>
                  <!--Optional:-->
                  <loc:TypeClient>?</loc:TypeClient>
                  <!--Optional:-->
                  <loc:StatutEconomique>?</loc:StatutEconomique>
                  <!--Optional:-->
                  <loc:Extranet>?</loc:Extranet>
                  <!--Optional:-->
                  <loc:UnikCall>?</loc:UnikCall>
                  <!--Optional:-->
                  <loc:CodeClientSiren>?</loc:CodeClientSiren>
                  <!--Optional:-->
                  <loc:InfoChantier>
                     <loc:CAFacture>?</loc:CAFacture>
                  </loc:InfoChantier>
               </loc:FicheClient>
               <!--Optional:-->
               <loc:AdresseClient>
                  <!--Optional:-->
                  <loc:IdentificationOrganisation>?</loc:IdentificationOrganisation>
                  <!--Optional:-->
                  <loc:ComplementNom>?</loc:ComplementNom>
                  <!--Optional:-->
                  <loc:ComplementAdresse>?</loc:ComplementAdresse>
                  <!--Optional:-->
                  <loc:Numero_et_rue>?</loc:Numero_et_rue>
                  <!--Optional:-->
                  <loc:MentionSpeciale>?</loc:MentionSpeciale>
                  <!--Optional:-->
                  <loc:Codepostal>?</loc:Codepostal>
                  <!--Optional:-->
                  <loc:Localite>?</loc:Localite>
                  <!--Optional:-->
                  <loc:Pays>?</loc:Pays>
               </loc:AdresseClient>
               <!--Optional:-->
               <loc:CommunicationsClients>
                  <!--Zero or more repetitions:-->
                  <loc:CommunicationsClient>
                     <loc:Type>?</loc:Type>
                     <loc:Nature>?</loc:Nature>
                     <loc:Value>?</loc:Value>
                  </loc:CommunicationsClient>
               </loc:CommunicationsClients>
            </loc:Client>
         </loc:Clients>
      </loc:WS_WCLIENT_RECH_2>
   </soapenv:Body>
</soapenv:Envelope>