version: '2.1'
services:
  db-mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=task_manager
      - MYSQL_ROOT_PASSWORD=secret
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
    ports:
      - "3306:3306"
